// Studio config holds metadata and filters for each scraper.
export default [
  {
    key: "visceral",
    studioId: 1,
    studioName: "Visceral Dance Chicago",
    scheduleUrl: "https://www.visceraldance.com/classschedule",
    allowedStyles: [
      "hip hop",
      "hip-hop",
      "open",
      "k-pop",
      "kpop",
      "heels",
      "wacking",
      "waacking",
      "vogue",
      "vouge",
      "jazz",
      "contemporary",
      "ballet",
      "tap",
      "modern",
    ],
    skipKeywords: [
      "youth",
      "kids",
      "kid",
      "children",
      "closed",
      "virtual",
      "pilates",
      "bemoved",
    ],
  },
  // Other studios can stay listed until their scrapers exist.
  {
    key: "puzzlebox",
    studioId: 2,
    studioName: "The Puzzle Box Dance Studio",
    scheduleUrl: "https://www.thepuzzleboxdancestudio.com/book-by-calendar",
    allowedStyles: null,
    skipKeywords: ["kids"],
  },
  {
    key: "danceforever",
    studioId: 5,
    studioName: "Dance Forever",
    scheduleUrl: "https://www.dance-forever.com/schedule",
    allowedStyles: null,
    skipKeywords: ["cardio"],
  },
  {
    key: "indiemedia",
    studioId: 4,
    studioName: "Indie Media Studio",
    scheduleUrl: "https://www.indiemediastudio.com/",
    // Require "class" to skip non-class events.
    allowedStyles: ["class"],
    skipKeywords: ["day pass", "academy"],
  },
];
